### ISSUE TITLE
Maak aub geen divjes indien er niks mee gedaan wordt, je kan bijvoorbeeld kiezen voor een Article in je ssection

### ISSUE THREAD

**Issue by modous** [Davidvboxt/performance-matters-optimized-website#22]
https://github.com/Davidvboxt/performance-matters-optimized-website/blob/b8da5a78f41fa819c75e7375deedd55b1b3108ad/views/index.ejs#L4-L10

**Comment by Davidvboxt** [comment]
De div had ik nodig om te gebruiken voor het centeren en een wijdde geven voor alles wat in de div plaats vind.
