### ISSUE TITLE
STYLING IN JE EJS FILE???????? beter in de css file

### ISSUE THREAD

**Issue by modous** [Davidvboxt/performance-matters-optimized-website#30]
https://github.com/Davidvboxt/performance-matters-optimized-website/blob/b8da5a78f41fa819c75e7375deedd55b1b3108ad/views/success.ejs#L6-L68

**Comment by amirdev98** [comment]
Ja, ik dacht aan performance, om de website sneller te laten laden, maar ik heb nu alle css in de algemene bestand geplakt en de elementen een specifieke class gegeven.
