### ISSUE TITLE
Je pagina is gemixt met Engelse en Nederlandse woorden. Probeer je te houden aan 1 taal

### ISSUE THREAD

**Issue by Davidvboxt** [Davidvboxt/performance-matters-optimized-website#32]
https://github.com/Davidvboxt/performance-matters-optimized-website/blob/b8da5a78f41fa819c75e7375deedd55b1b3108ad/views/success.ejs#L74

**Comment by amirdev98** [comment]
Ja dat moest ik nog ff fixen, dankjewel voor je opmerking!

**Comment by amirdev98** [comment]
ik heb het veranderd naar Nederlands

**Comment by amirdev98** [comment]
Dankjewel voor je feedback!
